export type Room = {
  id: string;
  name: string;
  x: number;
  y: number;
  width: number;
  height: number;
  type: "room" | "lab" | "office" | "stairs" | "free";
};

export type Floor = {
  floorNumber: number;
  rooms: Room[];
  planImage?: string;
};

export const SUMANADASA_FLOORS: Floor[] = [
  {
    floorNumber: 0,
    rooms: [
      {
        id: "ee1_1",
        name: "Room 101",
        x: 10,
        y: 10,
        width: 80,
        height: 120,
        type: "room",
      },
      {
        id: "ee1_2",
        name: "Lab 102",
        x: 90,
        y: 10,
        width: 80,
        height: 120,
        type: "lab",
      },
      {
        id: "ee1_3",
        name: "Room 103",
        x: 170,
        y: 10,
        width: 110,
        height: 120,
        type: "room",
      },
      {
        id: "ee1_4",
        name: "Lab 104",
        x: 280,
        y: 10,
        width: 110,
        height: 120,
        type: "lab",
      },
      {
        id: "ee1_5",
        name: "Lab 105",
        x: 390,
        y: 10,
        width: 80,
        height: 120,
        type: "lab",
      },
      {
        id: "ee1_6",
        name: "Lab 106",
        x: 470,
        y: 10,
        width: 70,
        height: 120,
        type: "lab",
      },
      {
        id: "ee1_7",
        name: "Lab 107",
        x: 540,
        y: 10,
        width: 60,
        height: 120,
        type: "lab",
      },
      {
        id: "ee1_8",
        name: "Lab 108",
        x: 600,
        y: 10,
        width: 80,
        height: 120,
        type: "lab",
      },
      {
        id: "ee1_9",
        name: "Lab 109",
        x: 680,
        y: 10,
        width: 110,
        height: 120,
        type: "lab",
      },
      {
        id: "ee1_10",
        name: "Room 110",
        x: 10,
        y: 130,
        width: 80,
        height: 100,
        type: "room",
      },
      {
        id: "ee1_11",
        name: "Lab 111",
        x: 10,
        y: 230,
        width: 80,
        height: 100,
        type: "lab",
      },
      {
        id: "ee1_12",
        name: "Lecture Hall A",
        x: 110,
        y: 150,
        width: 200,
        height: 190,
        type: "room",
      },
      {
        id: "ee1_13",
        name: "Lecture Hall B",
        x: 410,
        y: 150,
        width: 300,
        height: 190,
        type: "room",
      }, 
      {
        id: "ee1_14",
        name: "Stairs 1",
        x: 315,
        y: 150,
        width: 60,
        height: 70,
        type: "stairs",
      },
      {
        id: "ee1_15",
        name: "Stairs 2",
        x: 315,
        y: 270,
        width: 60,
        height: 70,
        type: "stairs",
      },
      {
        id: "ee1_16",
        name: "Room 112",
        x: 740,
        y: 130,
        width: 50,
        height: 250,
        type: "room",
      }, 
      {
        id: "ee1_17",
        name: "Office 113",
        x: 10,
        y: 330,
        width: 80,
        height: 160,
        type: "room",
      },
      {
        id: "ee1_18",
        name: "Office 114",
        x: 90,
        y: 370,
        width: 100,
        height: 120,
        type: "office",
      },
      {
        id: "ee1_19",
        name: "Office 115",
        x: 190,
        y: 370,
        width: 200,
        height: 120,
        type: "office",
      },
      {
        id: "ee1_20",
        name: "Lab 116",
        x: 390,
        y: 370,
        width: 100,
        height: 120,
        type: "lab",
      },
      {
        id: "ee1_21",
        name: "Lab 117",
        x: 490,
        y: 370,
        width: 130,
        height: 120,
        type: "lab",
      },
      {
        id: "ee1_22",
        name: "Lab 118",
        x: 620,
        y: 370,
        width: 170,
        height: 120,
        type: "lab",
      },
    ],
  },
  {
    floorNumber: 1,
    rooms: [
      {
        id: "ee2_1",
        name: " ",
        x: 10,
        y: 10,
        width: 300,
        height: 120,
        type: "room",
      },
      {
        id: "ee2_2",
        name: " ",
        x: 410,
        y: 10,
        width: 380,
        height: 120,
        type: "lab",
      },
      {
        id: "ee2_3",
        name: " ",
        x: 10,
        y: 130,
        width: 80,
        height: 360,
        type: "room",
      },
      {
        id: "ee2_4",
        name: "Open Area",
        x: 110,
        y: 150,
        width: 200,
        height: 190,
        type: "room",
      }, 
      {
        id: "ee2_5",
        name: "Open Area",
        x: 410,
        y: 150,
        width: 300,
        height: 190,
        type: "room",
      }, 
      {
        id: "ee2_6",
        name: "Stair_1",
        x: 315,
        y: 150,
        width: 60,
        height: 70,
        type: "stairs",
      },
      {
        id: "ee2_7",
        name: "Stair_2",
        x: 315,
        y: 270,
        width: 60,
        height: 70,
        type: "stairs",
      },
      {
        id: "ee2_8",
        name: " ",
        x: 740,
        y: 130,
        width: 50,
        height: 240,
        type: "room",
      },
      {
        id: "ee2_9",
        name: "Room 215",
        x: 90,
        y: 370,
        width: 100,
        height: 120,
        type: "office",
      },
      {
        id: "ee2_10",
        name: " ",
        x: 190,
        y: 370,
        width: 430,
        height: 120,
        type: "office",
      },

      {
        id: "ee2_11",
        name: "Lecture Hall",
        x: 620,
        y: 370,
        width: 170,
        height: 120,
        type: "room",
      },
    ],
  },
  {
    floorNumber: 2,
    rooms: [
      {
        id: "cse1_seminar",
        name: "Seminar Room",
        x: 10,
        y: 10,
        width: 80,
        height: 120,
        type: "room",
      },
      {
        id: "cse1_codegen",
        name: "CodeGen Lab",
        x: 90,
        y: 10,
        width: 80,
        height: 120,
        type: "lab",
      },
      {
        id: "cse1_sysco",
        name: "Sysco LABS Lounge",
        x: 170,
        y: 10,
        width: 110,
        height: 120,
        type: "room",
      },
      {
        id: "cse1_insight",
        name: "Insight Hub",
        x: 280,
        y: 10,
        width: 110,
        height: 120,
        type: "lab",
      },
      {
        id: "cse1_network",
        name: "Network Lab",
        x: 390,
        y: 10,
        width: 80,
        height: 120,
        type: "lab",
      },
      {
        id: "cse1_embedded",
        name: "Embedded Lab",
        x: 470,
        y: 10,
        width: 70,
        height: 120,
        type: "lab",
      },
      {
        id: "cse1_hpc",
        name: "HPC Lab",
        x: 540,
        y: 10,
        width: 60,
        height: 120,
        type: "lab",
      },
      {
        id: "cse1_intell",
        name: "IntelliSense Lab",
        x: 600,
        y: 10,
        width: 80,
        height: 120,
        type: "lab",
      },
      {
        id: "cse1_l3",
        name: "L3 Lab",
        x: 680,
        y: 10,
        width: 110,
        height: 120,
        type: "lab",
      },
      {
        id: "cse1_studio",
        name: "Studio",
        x: 10,
        y: 130,
        width: 80,
        height: 100,
        type: "room",
      },
      {
        id: "cse1_oldcodegen",
        name: "OLD CodeGen Lab",
        x: 10,
        y: 230,
        width: 80,
        height: 100,
        type: "lab",
      },
      {
        id: "cse1_atrium_1",
        name: "Open Area",
        x: 110,
        y: 150,
        width: 200,
        height: 190,
        type: "room",
      }, 
      {
        id: "cse1_atrium_2",
        name: "Open Area",
        x: 410,
        y: 150,
        width: 300,
        height: 190,
        type: "room",
      }, 
      {
        id: "cse1_stairs_1",
        name: "Stairs 1",
        x: 315,
        y: 150,
        width: 60,
        height: 70,
        type: "stairs",
      },
      {
        id: "cse1_stairs_2",
        name: "Stairs 2",
        x: 315,
        y: 270,
        width: 60,
        height: 70,
        type: "stairs",
      },
      {
        id: "cse1_instructor",
        name: "Instructor room",
        x: 740,
        y: 130,
        width: 50,
        height: 240,
        type: "room",
      }, 
      {
        id: "cse1_server",
        name: "Server Room",
        x: 10,
        y: 330,
        width: 80,
        height: 160,
        type: "room",
      },
      {
        id: "cse1_ice",
        name: "ICE Room",
        x: 90,
        y: 370,
        width: 100,
        height: 120,
        type: "office",
      },
      {
        id: "cse1_staff2",
        name: "Staff Room",
        x: 190,
        y: 370,
        width: 200,
        height: 120,
        type: "office",
      },
      {
        id: "cse1_ra",
        name: "RA Lab",
        x: 390,
        y: 370,
        width: 100,
        height: 120,
        type: "lab",
      },
      {
        id: "cse1_gtn",
        name: "GTN Lab",
        x: 490,
        y: 370,
        width: 130,
        height: 120,
        type: "lab",
      },
      {
        id: "cse1_research",
        name: "Research Lab",
        x: 620,
        y: 370,
        width: 170,
        height: 120,
        type: "lab",
      },
    ],
  },
  {
    floorNumber: 3,
    rooms: [
      {
        id: "cse2_1",
        name: "SLIoT Lab",
        x: 10,
        y: 10,
        width: 100,
        height: 120,
        type: "lab",
      },

      {
        id: "cse2_2",
        name: "Advanced Lab",
        x: 110,
        y: 10,
        width: 140,
        height: 120,
        type: "lab",
      },
      {
        id: "cse2_3",
        name: "Level 2 Lab",
        x: 250,
        y: 10,
        width: 140,
        height: 120,
        type: "lab",
      },
      {
        id: "cse2_4",
        name: " ",
        x: 390,
        y: 10,
        width: 400,
        height: 120,
        type: "room",
      },
      {
        id: "cse2_5",
        name: " ",
        x: 10,
        y: 130,
        width: 80,
        height: 360,
        type: "room",
      },

      {
        id: "cse2_6",
        name: "Open Area",
        x: 110,
        y: 150,
        width: 200,
        height: 190,
        type: "room",
      }, 
      {
        id: "cse2_7",
        name: "Open Area",
        x: 410,
        y: 150,
        width: 300,
        height: 190,
        type: "room",
      }, 
      {
        id: "cse2_8",
        name: "Stairs 1",
        x: 315,
        y: 150,
        width: 60,
        height: 70,
        type: "stairs",
      },
      {
        id: "cse2_9",
        name: "Stairs 2",
        x: 315,
        y: 270,
        width: 60,
        height: 70,
        type: "stairs",
      },
      {
        id: "cse2_10",
        name: " ",
        x: 740,
        y: 130,
        width: 50,
        height: 240,
        type: "room",
      }, 
      {
        id: "cse2_11",
        name: "Auditorium",
        x: 90,
        y: 370,
        width: 200,
        height: 120,
        type: "room",
      },
      {
        id: "cse2_12",
        name: "Mini Auditorium",
        x: 290,
        y: 370,
        width: 150,
        height: 120,
        type: "office",
      },
      {
        id: "cse2_13",
        name: " ",
        x: 440,
        y: 370,
        width: 350,
        height: 120,
        type: "lab",
      },
    ],
  },
];

export const IT_FLOORS: Floor[] = [
  {
    floorNumber: 0,
    rooms: [
      {
        id: "it_lobby",
        name: "Lobby",
        x: 50,
        y: 50,
        width: 300,
        height: 200,
        type: "room",
      },
      {
        id: "it_stairs_0",
        name: "Main Stairs",
        x: 400,
        y: 50,
        width: 100,
        height: 100,
        type: "stairs",
      },
    ],
  },
  {
    floorNumber: 1,
    rooms: [
      {
        id: "it_lab1",
        name: "Computer Lab 1",
        x: 50,
        y: 50,
        width: 250,
        height: 150,
        type: "lab",
      },
      {
        id: "it_stairs_1",
        name: "Main Stairs",
        x: 400,
        y: 50,
        width: 100,
        height: 100,
        type: "stairs",
      },
    ],
  },
  {
    floorNumber: 2,
    rooms: [
      {
        id: "it_lab2",
        name: "Computer Lab 2",
        x: 50,
        y: 50,
        width: 250,
        height: 150,
        type: "lab",
      },
      {
        id: "it_stairs_2",
        name: "Main Stairs",
        x: 400,
        y: 50,
        width: 100,
        height: 100,
        type: "stairs",
      },
    ],
  },
  {
    floorNumber: 3,
    rooms: [
      {
        id: "it_office",
        name: "Staff Office",
        x: 50,
        y: 50,
        width: 200,
        height: 150,
        type: "office",
      },
      {
        id: "it_stairs_3",
        name: "Main Stairs",
        x: 400,
        y: 50,
        width: 100,
        height: 100,
        type: "stairs",
      },
    ],
  },
  {
    floorNumber: 4,
    rooms: [
      {
        id: "it_research",
        name: "Research Center",
        x: 50,
        y: 50,
        width: 300,
        height: 200,
        type: "lab",
      },
      {
        id: "it_stairs_4",
        name: "Main Stairs",
        x: 400,
        y: 50,
        width: 100,
        height: 100,
        type: "stairs",
      },
    ],
  },
  {
    floorNumber: 5,
    rooms: [
      {
        id: "it_roof",
        name: "Rooftop Terrace",
        x: 50,
        y: 50,
        width: 400,
        height: 300,
        type: "room",
      },
      {
        id: "it_stairs_5",
        name: "Main Stairs",
        x: 450,
        y: 250,
        width: 100,
        height: 100,
        type: "stairs",
      },
    ],
  },
];

export const LIBRARY_FLOORS: Floor[] = [
  {
    floorNumber: -1,
    //planImage: "/floor plans/Library/01 basement-1_3.jpg",
    rooms: [
      {
        id: "lib_1",
        name: "Study Booths",
        x: 10,
        y: 30,
        width: 800,
        height: 200,
        type: "room",
      },
      {
        id: "lib_2",
        name: " ",
        x: 10,
        y: 230,
        width: 800,
        height: 250,
        type: "room",
      },
      {
        id: "lib_3",
        name: "Stairs 1",
        x: 10,
        y: 230,
        width: 60,
        height: 60,
        type: "stairs",
      },
      {
        id: "lib_4",
        name: "Stairs 2",
        x: 750,
        y: 230,
        width: 60,
        height: 60,
        type: "stairs",
      },
    ],
  },
  {
    floorNumber: 0,
    rooms: [
      {
        id: "lib0_itunit",
        name: "ITunit (NDT)",
        x: 10,
        y: 30,
        width: 200,
        height: 120,
        type: "room",
      },

      {
        id: "lib0_complab",
        name: "Computer Lab",
        x: 330,
        y: 30,
        width: 280,
        height: 120,
        type: "lab",
      },
      {
        id: "lib0_seminar",
        name: "Seminar Room",
        x: 610,
        y: 30,
        width: 180,
        height: 140,
        type: "room",
      },
      {
        id: "lib0_toilet",
        name: "Wash room",
        x: 10,
        y: 150,
        width: 80,
        height: 180,
        type: "free",
      },
      {
        id: "lib0_store",
        name: "Store Room",
        x: 90,
        y: 150,
        width: 120,
        height: 90,
        type: "room",
      },
      {
        id: "lib0_staff_lounge",
        name: "Staff Lounge",
        x: 520,
        y: 150,
        width: 90,
        height: 120,
        type: "room",
      },
      {
        id: "lib0_ladies_lunch",
        name: "Lunch Room",
        x: 610,
        y: 170,
        width: 120,
        height: 100,
        type: "room",
      },
      {
        id: "lib0_wc",
        name: "Other",
        x: 730,
        y: 170,
        width: 60,
        height: 160,
        type: "free",
      },

      // Stairs
      {
        id: "lib0_stairs_1",
        name: "Stairs 1",
        x: 150,
        y: 240,
        width: 60,
        height: 60,
        type: "stairs",
      },
      {
        id: "lib0_stairs_2",
        name: "Stairs 2",
        x: 610,
        y: 270,
        width: 60,
        height: 60,
        type: "stairs",
      },
      {
        id: "lib0_bindery",
        name: "Bindery Section",
        x: 10,
        y: 330,
        width: 200,
        height: 140,
        type: "room",
      },
      {
        id: "lib0_bindery_stores",
        name: "Bindery Stores",
        x: 210,
        y: 330,
        width: 100,
        height: 140,
        type: "room",
      },
      {
        id: "lib0_aq_stores",
        name: "AQ Stores",
        x: 310,
        y: 330,
        width: 120,
        height: 140,
        type: "room",
      },
      {
        id: "lib0_tech_services",
        name: "Technical Services",
        x: 430,
        y: 330,
        width: 200,
        height: 140,
        type: "room",
      },
      {
        id: "lib0_gents_lunch",
        name: "Gents Lunch Room",
        x: 630,
        y: 330,
        width: 160,
        height: 140,
        type: "room",
      },
    ],
  },
  {
    floorNumber: 1,
    rooms: [
      {
        id: "lib1_discussion",
        name: "Discussion Room",
        x: 10,
        y: 30,
        width: 200,
        height: 210,
        type: "room",
      },
      {
        id: "lib1_lab",
        name: "Computer Laboratory",
        x: 210,
        y: 30,
        width: 300,
        height: 210,
        type: "lab",
      },
      {
        id: "lib1_auditorium",
        name: "Auditorium",
        x: 510,
        y: 30,
        width: 280,
        height: 240,
        type: "room",
      },
      {
        id: "lib1_stairs_1",
        name: "Stairs 1",
        x: 150,
        y: 240,
        width: 60,
        height: 60,
        type: "stairs",
      },
      {
        id: "lib1_stairs_2",
        name: "Stairs 2",
        x: 610,
        y: 270,
        width: 60,
        height: 60,
        type: "stairs",
      },
      {
        id: "lib1_al_section",
        name: "A/L Section",
        x: 10,
        y: 300,
        width: 220,
        height: 160,
        type: "room",
      },
      {
        id: "lib1_dlandas",
        name: "Dlandas",
        x: 230,
        y: 390,
        width: 100,
        height: 70,
        type: "room",
      },
      {
        id: "lib1_periodicals",
        name: "Periodicals & Shelves",
        x: 330,
        y: 330,
        width: 460,
        height: 130,
        type: "free",
      },
      {
        id: "lib1_free1",
        name: " ",
        x: 700,
        y: 270,
        width: 90,
        height: 60,
        type: "free",
      },
      {
        id: "lib1_free2",
        name: " ",
        x: 10,
        y: 240,
        width: 90,
        height: 60,
        type: "free",
      },
    ],
  },
  {
    floorNumber: 2,
    rooms: [
      {
        id: "lib2_study_area",
        name: "Study Area",
        x: 10,
        y: 30,
        width: 780,
        height: 170,
        type: "free",
      },
      {
        id: "lib2_tea_room",
        name: " ",
        x: 10,
        y: 200,
        width: 80,
        height: 100,
        type: "free",
      },
      {
        id: "lib2_stairs_1",
        name: "Stairs 1",
        x: 150,
        y: 240,
        width: 60,
        height: 60,
        type: "stairs",
      },
      {
        id: "lib2_stairs_2",
        name: "Stairs 2",
        x: 610,
        y: 270,
        width: 60,
        height: 60,
        type: "stairs",
      },
      {
        id: "lib2_inquiries",
        name: "Inquiries",
        x: 330,
        y: 370,
        width: 100,
        height: 100,
        type: "office",
      },
      {
        id: "lib2_cites",
        name: "CITES Area",
        x: 10,
        y: 300,
        width: 220,
        height: 170,
        type: "room",
      },
      {
        id: "lib2_membership",
        name: "Membership Office",
        x: 230,
        y: 370,
        width: 100,
        height: 100,
        type: "office",
      },
      {
        id: "lib2_cloak",
        name: "Cloak Room",
        x: 430,
        y: 370,
        width: 70,
        height: 100,
        type: "room",
      },
      {
        id: "lib2_lounge",
        name: "Lounge & Learning Commons",
        x: 500,
        y: 330,
        width: 290,
        height: 140,
        type: "room",
      },
      {
        id: "lib2_free",
        name: " ",
        x: 690,
        y: 200,
        width: 100,
        height: 130,
        type: "free",
      },
    ],
  },
  {
    floorNumber: 3,
    rooms: [
      {
        id: "lib3_server",
        name: "Server Room",
        x: 10,
        y: 30,
        width: 80,
        height: 100,
        type: "room",
      },
      {
        id: "lib3_librarian",
        name: "Librarian Office",
        x: 10,
        y: 130,
        width: 120,
        height: 80,
        type: "office",
      },
      {
        id: "lib3_ts01",
        name: " TS 01",
        x: 90,
        y: 30,
        width: 150,
        height: 100,
        type: "office",
      },
      {
        id: "lib3_stairs_1",
        name: "Stairs 1",
        x: 150,
        y: 240,
        width: 60,
        height: 60,
        type: "stairs",
      },
      {
        id: "lib3_stairs_2",
        name: "Stairs 2",
        x: 610,
        y: 270,
        width: 60,
        height: 60,
        type: "stairs",
      },
      {
        id: "lib3_discussion",
        name: "Discussions Room",
        x: 520,
        y: 190,
        width: 270,
        height: 80,
        type: "room",
      },
      {
        id: "lib3_free",
        name: " ",
        x: 690,
        y: 270,
        width: 100,
        height: 60,
        type: "free",
      },
      {
        id: "lib3_admin",
        name: "Admin Office",
        x: 10,
        y: 210,
        width: 120,
        height: 80,
        type: "office",
      },
      {
        id: "lib3_avto",
        name: "AVTO & TO",
        x: 10,
        y: 290,
        width: 120,
        height: 100,
        type: "room",
      },
      {
        id: "lib3_al_it",
        name: "AL/IT Section",
        x: 10,
        y: 390,
        width: 120,
        height: 80,
        type: "room",
      },
      {
        id: "lib3_shelves_1",
        name: "Book Shelves",
        x: 240,
        y: 30,
        width: 550,
        height: 160,
        type: "free",
      },
      {
        id: "lib3_shelves_2",
        name: "Book Shelves",
        x: 130,
        y: 330,
        width: 660,
        height: 140,
        type: "free",
      },
    ],
  },
];

export const BUILDING_DATA: Record<
  string,
  { name: string; floors: Floor[]; minFloor: number; maxFloor: number }
> = {
  cse: {
    name: "Sumanadasa Building",
    floors: SUMANADASA_FLOORS,
    minFloor: 0,
    maxFloor: 3,
  },
  it: {
    name: "Faculty of IT",
    floors: IT_FLOORS,
    minFloor: 0,
    maxFloor: 5,
  },
  library: {
    name: "Library",
    floors: LIBRARY_FLOORS,
    minFloor: -1,
    maxFloor: 3,
  },
};
