export type Room = {
  id: string;
  name: string;
  x: number;
  y: number;
  width: number;
  height: number;
  type: "room" | "lab" | "office" | "stairs" | "free";
};

export type Floor = {
  floorNumber: number;
  rooms: Room[];
  planImage?: string;
};

export const SUMANADASA_FLOORS: Floor[] = [
  {
    floorNumber: 0,
    rooms: [
      { id: "sumanadasa-f1-cls-a", name: "Classroom A", x: 50, y: 50, width: 340, height: 200, type: "room" },
      { id: "sumanadasa-f1-cls-b", name: "Classroom B", x: 410, y: 50, width: 340, height: 200, type: "room" },
      { id: "sumanadasa-f1-lab", name: "Main Lab", x: 50, y: 270, width: 340, height: 180, type: "lab" },
      { id: "sumanadasa-f1-office", name: "Dept Office", x: 410, y: 270, width: 340, height: 180, type: "office" },
      { id: "sumanadasa-f1-stairs-1", name: "Stairs 1", x: 315, y: 150, width: 60, height: 70, type: "stairs" },
      { id: "sumanadasa-f1-stairs-2", name: "Stairs 2", x: 315, y: 270, width: 60, height: 70, type: "stairs" },
    ],
  },
  {
    floorNumber: 1,
    rooms: [
      { id: "sumanadasa-f2-seminar", name: "Seminar Room", x: 10, y: 10, width: 80, height: 120, type: "room" },
      { id: "sumanadasa-f2-codegen-lab", name: "CodeGen Lab", x: 90, y: 10, width: 80, height: 120, type: "lab" },
      { id: "sumanadasa-f2-sysco-lounge", name: "Sysco LABS Lounge", x: 170, y: 10, width: 110, height: 120, type: "room" },
      { id: "sumanadasa-f2-insight-hub", name: "Insight Hub", x: 280, y: 10, width: 110, height: 120, type: "lab" },
      { id: "sumanadasa-f2-network-lab", name: "Network Lab", x: 390, y: 10, width: 80, height: 120, type: "lab" },
      { id: "sumanadasa-f2-embedded-lab", name: "Embedded Lab", x: 470, y: 10, width: 70, height: 120, type: "lab" },
      { id: "sumanadasa-f2-hpc-lab", name: "HPC Lab", x: 540, y: 10, width: 60, height: 120, type: "lab" },
      { id: "sumanadasa-f2-intellisense-lab", name: "IntelliSense Lab", x: 600, y: 10, width: 80, height: 120, type: "lab" },
      { id: "sumanadasa-f2-l3-lab", name: "L3 Lab", x: 680, y: 10, width: 110, height: 120, type: "lab" },
      { id: "sumanadasa-f2-studio", name: "Studio", x: 10, y: 130, width: 80, height: 100, type: "room" },
      { id: "sumanadasa-f2-oldcodegen-lab", name: "OLD CodeGen Lab", x: 10, y: 230, width: 80, height: 100, type: "lab" },
      { id: "sumanadasa-f2-open-area-n", name: "Open Area", x: 110, y: 150, width: 200, height: 190, type: "room" }, 
      { id: "sumanadasa-f2-open-area-s", name: "Open Area", x: 410, y: 150, width: 300, height: 190, type: "room" }, 
      { id: "sumanadasa-f2-stairs-1", name: "Stairs 1", x: 315, y: 150, width: 60, height: 70, type: "stairs" },
      { id: "sumanadasa-f2-stairs-2", name: "Stairs 2", x: 315, y: 270, width: 60, height: 70, type: "stairs" },
      { id: "sumanadasa-f2-instructor-room", name: "Instructor room", x: 740, y: 130, width: 50, height: 240, type: "room" }, 
      { id: "sumanadasa-f2-server", name: "Server Room", x: 10, y: 330, width: 80, height: 160, type: "room" },
      { id: "sumanadasa-f2-ice-room", name: "ICE Room", x: 90, y: 370, width: 100, height: 120, type: "office" },
      { id: "sumanadasa-f2-staff-room", name: "Staff Room", x: 190, y: 370, width: 200, height: 120, type: "office" },
      { id: "sumanadasa-f2-ra-lab", name: "RA Lab", x: 390, y: 370, width: 100, height: 120, type: "lab" },
      { id: "sumanadasa-f2-gtn-lab", name: "GTN Lab", x: 490, y: 370, width: 130, height: 120, type: "lab" },
      { id: "sumanadasa-f2-research-lab", name: "Research Lab", x: 620, y: 370, width: 170, height: 120, type: "lab" },
    ],
  },
  {
    floorNumber: 2,
    rooms: [
      { id: "sumanadasa-f3-cls-a", name: "Classroom A", x: 50, y: 50, width: 340, height: 200, type: "room" },
      { id: "sumanadasa-f3-cls-b", name: "Classroom B", x: 410, y: 50, width: 340, height: 200, type: "room" },
      { id: "sumanadasa-f3-lab", name: "Main Lab", x: 50, y: 270, width: 340, height: 180, type: "lab" },
      { id: "sumanadasa-f3-office", name: "Dept Office", x: 410, y: 270, width: 340, height: 180, type: "office" },
      { id: "sumanadasa-f3-stairs-1", name: "Stairs 1", x: 315, y: 150, width: 60, height: 70, type: "stairs" },
      { id: "sumanadasa-f3-stairs-2", name: "Stairs 2", x: 315, y: 270, width: 60, height: 70, type: "stairs" },
    ],
  },
  {
    floorNumber: 3,
    rooms: [
      { id: "sumanadasa-f4-cls-a", name: "Classroom A", x: 50, y: 50, width: 340, height: 200, type: "room" },
      { id: "sumanadasa-f4-cls-b", name: "Classroom B", x: 410, y: 50, width: 340, height: 200, type: "room" },
      { id: "sumanadasa-f4-lab", name: "Main Lab", x: 50, y: 270, width: 340, height: 180, type: "lab" },
      { id: "sumanadasa-f4-office", name: "Dept Office", x: 410, y: 270, width: 340, height: 180, type: "office" },
      { id: "sumanadasa-f4-stairs-1", name: "Stairs 1", x: 315, y: 150, width: 60, height: 70, type: "stairs" },
      { id: "sumanadasa-f4-stairs-2", name: "Stairs 2", x: 315, y: 270, width: 60, height: 70, type: "stairs" },
    ],
  },
];

export const IT_FLOORS: Floor[] = [
  {
    floorNumber: 0,
    rooms: [
      {
        id: "it_lobby",
        name: "Lobby",
        x: 50,
        y: 50,
        width: 300,
        height: 200,
        type: "room",
      },
      {
        id: "it_stairs",
        name: "Main Stairs",
        x: 400,
        y: 50,
        width: 100,
        height: 100,
        type: "stairs",
      },
    ],
  },
  {
    floorNumber: 1,
    rooms: [
      {
        id: "it_lab1",
        name: "Computer Lab 1",
        x: 50,
        y: 50,
        width: 250,
        height: 150,
        type: "lab",
      },
      {
        id: "it_stairs",
        name: "Main Stairs",
        x: 400,
        y: 50,
        width: 100,
        height: 100,
        type: "stairs",
      },
    ],
  },
  {
    floorNumber: 2,
    rooms: [
      {
        id: "it_lab2",
        name: "Computer Lab 2",
        x: 50,
        y: 50,
        width: 250,
        height: 150,
        type: "lab",
      },
      {
        id: "it_stairs",
        name: "Main Stairs",
        x: 400,
        y: 50,
        width: 100,
        height: 100,
        type: "stairs",
      },
    ],
  },
  {
    floorNumber: 3,
    rooms: [
      {
        id: "it_office",
        name: "Staff Office",
        x: 50,
        y: 50,
        width: 200,
        height: 150,
        type: "office",
      },
      {
        id: "it_stairs",
        name: "Main Stairs",
        x: 400,
        y: 50,
        width: 100,
        height: 100,
        type: "stairs",
      },
    ],
  },
  {
    floorNumber: 4,
    rooms: [
      {
        id: "it_research",
        name: "Research Center",
        x: 50,
        y: 50,
        width: 300,
        height: 200,
        type: "lab",
      },
      {
        id: "it_stairs",
        name: "Main Stairs",
        x: 400,
        y: 50,
        width: 100,
        height: 100,
        type: "stairs",
      },
    ],
  },
  {
    floorNumber: 5,
    rooms: [
      {
        id: "it_roof",
        name: "Rooftop Terrace",
        x: 50,
        y: 50,
        width: 400,
        height: 300,
        type: "room",
      },
      {
        id: "it_stairs",
        name: "Main Stairs",
        x: 450,
        y: 250,
        width: 100,
        height: 100,
        type: "stairs",
      },
    ],
  },
];

export const LIBRARY_FLOORS: Floor[] = [
  {
    floorNumber: -1,
    //planImage: "/floor plans/Library/01 basement-1_3.jpg",
    rooms: [
      {
        id: "lib_1",
        name: "Study Booths",
        x: 10,
        y: 30,
        width: 800,
        height: 200,
        type: "room",
      },
      {
        id: "lib_2",
        name: " ",
        x: 10,
        y: 230,
        width: 800,
        height: 250,
        type: "room",
      },
      {
        id: "lib_3",
        name: "Stairs 1",
        x: 10,
        y: 230,
        width: 60,
        height: 60,
        type: "stairs",
      },
      {
        id: "lib_4",
        name: "Stairs 2",
        x: 750,
        y: 230,
        width: 60,
        height: 60,
        type: "stairs",
      },
    ],
  },
  {
    floorNumber: 0,
    rooms: [
      {
        id: "lib0_itunit",
        name: "ITunit (NDT)",
        x: 10,
        y: 30,
        width: 200,
        height: 120,
        type: "room",
      },

      {
        id: "lib0_complab",
        name: "Computer Lab",
        x: 330,
        y: 30,
        width: 280,
        height: 120,
        type: "lab",
      },
      {
        id: "lib0_seminar",
        name: "Seminar Room",
        x: 610,
        y: 30,
        width: 180,
        height: 140,
        type: "room",
      },
      {
        id: "lib0_toilet",
        name: "Wash room",
        x: 10,
        y: 150,
        width: 80,
        height: 180,
        type: "free",
      },
      {
        id: "lib0_store",
        name: "Store Room",
        x: 90,
        y: 150,
        width: 120,
        height: 90,
        type: "room",
      },
      {
        id: "lib0_staff_lounge",
        name: "Staff Lounge",
        x: 520,
        y: 150,
        width: 90,
        height: 120,
        type: "room",
      },
      {
        id: "lib0_ladies_lunch",
        name: "Lunch Room",
        x: 610,
        y: 170,
        width: 120,
        height: 100,
        type: "room",
      },
      {
        id: "lib0_wc",
        name: "Other",
        x: 730,
        y: 170,
        width: 60,
        height: 160,
        type: "free",
      },

      // Stairs
      {
        id: "lib0_stairs_1",
        name: "Stairs 1",
        x: 150,
        y: 240,
        width: 60,
        height: 60,
        type: "stairs",
      },
      {
        id: "lib0_stairs_2",
        name: "Stairs 2",
        x: 610,
        y: 270,
        width: 60,
        height: 60,
        type: "stairs",
      },
      {
        id: "lib0_bindery",
        name: "Bindery Section",
        x: 10,
        y: 330,
        width: 200,
        height: 140,
        type: "room",
      },
      {
        id: "lib0_bindery_stores",
        name: "Bindery Stores",
        x: 210,
        y: 330,
        width: 100,
        height: 140,
        type: "room",
      },
      {
        id: "lib0_aq_stores",
        name: "AQ Stores",
        x: 310,
        y: 330,
        width: 120,
        height: 140,
        type: "room",
      },
      {
        id: "lib0_tech_services",
        name: "Technical Services",
        x: 430,
        y: 330,
        width: 200,
        height: 140,
        type: "room",
      },
      {
        id: "lib0_gents_lunch",
        name: "Gents Lunch Room",
        x: 630,
        y: 330,
        width: 160,
        height: 140,
        type: "room",
      },
    ],
  },
  {
    floorNumber: 1,
    rooms: [
      {
        id: "lib1_discussion",
        name: "Discussion Room",
        x: 10,
        y: 30,
        width: 200,
        height: 210,
        type: "room",
      },
      {
        id: "lib1_lab",
        name: "Computer Laboratory",
        x: 210,
        y: 30,
        width: 300,
        height: 210,
        type: "lab",
      },
      {
        id: "lib1_auditorium",
        name: "Auditorium",
        x: 510,
        y: 30,
        width: 280,
        height: 240,
        type: "room",
      },
      {
        id: "lib0_stairs_1",
        name: "Stairs 1",
        x: 150,
        y: 240,
        width: 60,
        height: 60,
        type: "stairs",
      },
      {
        id: "lib0_stairs_2",
        name: "Stairs 2",
        x: 610,
        y: 270,
        width: 60,
        height: 60,
        type: "stairs",
      },
      {
        id: "lib1_al_section",
        name: "A/L Section",
        x: 10,
        y: 300,
        width: 220,
        height: 160,
        type: "room",
      },
      {
        id: "lib1_dlandas",
        name: "Dlandas",
        x: 230,
        y: 390,
        width: 100,
        height: 70,
        type: "room",
      },
      {
        id: "lib1_periodicals",
        name: "Periodicals & Shelves",
        x: 330,
        y: 330,
        width: 460,
        height: 130,
        type: "free",
      },
      {
        id: "lib1_free1",
        name: " ",
        x: 700,
        y: 270,
        width: 90,
        height: 60,
        type: "free",
      },
      {
        id: "lib1_free2",
        name: " ",
        x: 10,
        y: 240,
        width: 90,
        height: 60,
        type: "free",
      },
    ],
  },
  {
    floorNumber: 2,
    rooms: [
      {
        id: "lib2_study_area",
        name: "Study Area",
        x: 10,
        y: 30,
        width: 780,
        height: 170,
        type: "free",
      },
      {
        id: "lib2_tea_room",
        name: " ",
        x: 10,
        y: 200,
        width: 80,
        height: 100,
        type: "free",
      },
      {
        id: "lib0_stairs_1",
        name: "Stairs 1",
        x: 150,
        y: 240,
        width: 60,
        height: 60,
        type: "stairs",
      },
      {
        id: "lib0_stairs_2",
        name: "Stairs 2",
        x: 610,
        y: 270,
        width: 60,
        height: 60,
        type: "stairs",
      },
      {
        id: "lib2_inquiries",
        name: "Inquiries",
        x: 330,
        y: 370,
        width: 100,
        height: 100,
        type: "office",
      },
      {
        id: "lib2_cites",
        name: "CITES Area",
        x: 10,
        y: 300,
        width: 220,
        height: 170,
        type: "room",
      },
      {
        id: "lib2_membership",
        name: "Membership Office",
        x: 230,
        y: 370,
        width: 100,
        height: 100,
        type: "office",
      },
      {
        id: "lib2_cloak",
        name: "Cloak Room",
        x: 430,
        y: 370,
        width: 70,
        height: 100,
        type: "room",
      },
      {
        id: "lib2_lounge",
        name: "Lounge & Learning Commons",
        x: 500,
        y: 330,
        width: 290,
        height: 140,
        type: "room",
      },
      {
        id: "lib2_free",
        name: " ",
        x: 690,
        y: 200,
        width: 100,
        height: 130,
        type: "free",
      },
    ],
  },
  {
    floorNumber: 3,
    rooms: [
      {
        id: "lib3_server",
        name: "Server Room",
        x: 10,
        y: 30,
        width: 80,
        height: 100,
        type: "room",
      },
      {
        id: "lib3_librarian",
        name: "Librarian Office",
        x: 10,
        y: 130,
        width: 120,
        height: 80,
        type: "office",
      },
      {
        id: "lib3_ts01",
        name: " TS 01",
        x: 90,
        y: 30,
        width: 150,
        height: 100,
        type: "office",
      },
      {
        id: "lib0_stairs_1",
        name: "Stairs 1",
        x: 150,
        y: 240,
        width: 60,
        height: 60,
        type: "stairs",
      },
      {
        id: "lib0_stairs_2",
        name: "Stairs 2",
        x: 610,
        y: 270,
        width: 60,
        height: 60,
        type: "stairs",
      },
      {
        id: "lib3_discussion",
        name: "Discussions Room",
        x: 520,
        y: 190,
        width: 270,
        height: 80,
        type: "room",
      },
      {
        id: "lib3_free",
        name: " ",
        x: 690,
        y: 270,
        width: 100,
        height: 60,
        type: "free",
      },
      {
        id: "lib3_admin",
        name: "Admin Office",
        x: 10,
        y: 210,
        width: 120,
        height: 80,
        type: "office",
      },
      {
        id: "lib3_avto",
        name: "AVTO & TO",
        x: 10,
        y: 290,
        width: 120,
        height: 100,
        type: "room",
      },
      {
        id: "lib3_al_it",
        name: "AL/IT Section",
        x: 10,
        y: 390,
        width: 120,
        height: 80,
        type: "room",
      },
      {
        id: "lib3_shelves_1",
        name: "Book Shelves",
        x: 240,
        y: 30,
        width: 550,
        height: 160,
        type: "free",
      },
      {
        id: "lib3_shelves_2",
        name: "Book Shelves",
        x: 130,
        y: 330,
        width: 660,
        height: 140,
        type: "free",
      },
    ],
  },
];

export const BUILDING_DATA: Record<
  string,
  { name: string; floors: Floor[]; minFloor: number; maxFloor: number }
> = {
  cse: {
    name: "Sumanadasa Building",
    floors: SUMANADASA_FLOORS,
    minFloor: 0,
    maxFloor: 3,
  },
  it: {
    name: "Faculty of IT",
    floors: IT_FLOORS,
    minFloor: 0,
    maxFloor: 5,
  },
  library: {
    name: "Library",
    floors: LIBRARY_FLOORS,
    minFloor: -1,
    maxFloor: 3,
  },
};
